@startuml

entity Item {
    *label
    *slug
}

entity ItemValues {
    *label
    *value
    time
    startup_time
    total_percentage
}

entity Estimate {
    *label
    *total_time
}

entity EstimateLines {
    *label
    *time
    *type
}

Estimation ||--o{ EstimationLine
EstimationSettings ||--o{ EstimationSettingsValues
@enduml
