@startuml

entity Item {
    *label
    *slug
}

entity ItemValues {
    *label
    *value
    time
    startup_time
    total_percentage
}

entity Estimate {
    *label
    *total_time
}

entity EstimateLines {
    *label
    *time
    *type
}

Estimate ||--o{ EstimateLines
Item ||--o{ ItemValues
@enduml
